platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = '1'

# Load the Flutter podhelper from the standard location created by 'flutter pub get'
require File.expand_path(File.join('Flutter', 'podhelper'), __dir__)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Ensure all pod targets are also set to iOS 15.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end